# Generated by Django 6.0 on 2026-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('assigned_to', models.TextField()),
                ('priority', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
